import { describe, expect, it } from 'vitest'
import { renderImportReport } from '../src/run.js'

describe('renderImportReport', () => {
  const base = {
    ref: 'abc123',
    retrieved: '2026-08-01',
    upstream: 'https://github.com/cqframework/ecqm-content-qicore-2025',
  }

  it('accounts for every measure, imported and skipped', () => {
    const report = renderImportReport({
      ...base,
      imported: ['cms/a', 'cms/b'],
      skipped: [{ measure: 'CMS999Broken', reason: 'no parseable version' }],
    })
    expect(report).toContain('2 measures')
    expect(report).toContain('1 skipped')
    expect(report).toContain('CMS999Broken')
    expect(report).toContain('no parseable version')
  })

  it('states the pinned commit', () => {
    const report = renderImportReport({ ...base, imported: [], skipped: [] })
    expect(report).toContain('abc123')
  })

  it('says so plainly when nothing was skipped', () => {
    const report = renderImportReport({ ...base, imported: ['cms/a'], skipped: [] })
    expect(report).toContain('Nothing was skipped')
  })

  it('is generated, and says so, so nobody hand-edits it', () => {
    const report = renderImportReport({ ...base, imported: [], skipped: [] })
    expect(report).toContain('Generated by')
  })
})
