import { mkdir, rm, writeFile } from 'node:fs/promises'
import { basename, join } from 'node:path'
import { parseHeader } from './cql.js'
import { emitManifest, emitReadme, type PackagePlan } from './emit.js'
import { readMeasure } from './measure.js'
import { normalizeVersion, packageId, slugFor } from './naming.js'
import { planPackage, resolveLibraries, type ImportContext, type Skip } from './plan.js'
import { UPSTREAM, fetchUpstream, listCqlFiles, listMeasureFiles, readText } from './upstream.js'

export const MEASURES_DIR = 'measures/cms-fhir-2026'
export const REPORT_PATH = 'measures/import-report.md'

export interface ImportSummary {
  upstream: string
  ref: string
  retrieved: string
  imported: string[]
  skipped: Skip[]
}

export function renderImportReport(summary: ImportSummary): string {
  const lines: string[] = [
    '# Import report',
    '',
    `Generated by \`pnpm oq-import\`. Do not edit by hand: CI re-runs the importer and`,
    'fails if the committed tree differs from its output.',
    '',
    `Upstream: [${summary.upstream}](${summary.upstream})`,
    `Commit: \`${summary.ref}\``,
    `Retrieved: ${summary.retrieved}`,
    '',
    '## Result',
    '',
    `- ${summary.imported.length} measures imported`,
    `- ${summary.skipped.length} skipped`,
    '',
  ]

  lines.push('## Skipped', '')
  if (summary.skipped.length === 0) {
    lines.push('Nothing was skipped. Every upstream measure imported.', '')
  } else {
    lines.push(
      'Each of these was left out rather than guessed at. A skip is a gap in the',
      'corpus, not a silent omission.',
      '',
      '| Measure | Reason |',
      '|---------|--------|',
    )
    for (const skip of summary.skipped) lines.push(`| \`${skip.measure}\` | ${skip.reason} |`)
    lines.push('')
  }

  return lines.join('\n')
}

/**
 * Writes one self-contained package: the manifest, the README, the measure CQL,
 * and every library the measure includes. Vendoring the libraries is what makes
 * the package readable and evaluable on its own, which is the whole point of a
 * package. The alternative, publishing each shared library as its own package,
 * would require inventing a `measure.title` for something that is not a measure.
 */
async function writePackage(
  dir: string,
  plan: PackagePlan,
  cql: string,
  libraries: Map<string, string>,
): Promise<void> {
  await mkdir(join(dir, 'cql'), { recursive: true })
  await writeFile(join(dir, 'openquality.yaml'), emitManifest(plan))
  await writeFile(join(dir, 'README.md'), emitReadme(plan))
  await writeFile(join(dir, 'cql', plan.cqlFileName), cql)
  for (const name of plan.libraryFileNames) {
    const source = libraries.get(name.replace(/\.cql$/, ''))
    if (source !== undefined) await writeFile(join(dir, 'cql', name), source)
  }
}

/**
 * Imports the pinned upstream content into measures/. Removes the generated
 * directories first, so a measure that disappears upstream disappears here too
 * and the drift check stays meaningful.
 */
export async function runImport(retrieved: string, ref: string = UPSTREAM.ref): Promise<ImportSummary> {
  const root = await fetchUpstream(ref)
  const context: ImportContext = { upstream: UPSTREAM.url, ref, retrieved }

  const cqlByLibrary = new Map<string, string>()
  for (const path of await listCqlFiles(root)) {
    cqlByLibrary.set(basename(path, '.cql'), await readText(path))
  }

  await rm(MEASURES_DIR, { recursive: true, force: true })

  const imported: string[] = []
  const skipped: Skip[] = []

  for (const path of await listMeasureFiles(root)) {
    const measure = readMeasure(await readText(path))
    if (!measure) {
      skipped.push({ measure: basename(path, '.json'), reason: 'not a readable Measure resource' })
      continue
    }

    const source = measure.library ? cqlByLibrary.get(measure.library) : undefined
    if (!source) {
      skipped.push({ measure: measure.name, reason: `no CQL found for library "${measure.library ?? 'none'}"` })
      continue
    }

    const { plan, cql, skipped: skip } = planPackage(measure, source, context)
    if (!plan || !cql) {
      if (skip) skipped.push(skip)
      continue
    }

    // Libraries are vendored, so a missing one means the package would be
    // incomplete. Skip rather than ship something that cannot be evaluated.
    const { resolved, missing } = resolveLibraries(source, cqlByLibrary)
    if (missing.length > 0) {
      skipped.push({
        measure: measure.name,
        reason: `includes libraries not present upstream: ${missing.join(', ')}`,
      })
      continue
    }
    plan.libraryFileNames = resolved.map((name) => `${name}.cql`)

    await writePackage(join(MEASURES_DIR, plan.slug), plan, cql, cqlByLibrary)
    imported.push(plan.id)
  }

  const summary: ImportSummary = {
    upstream: UPSTREAM.url,
    ref,
    retrieved,
    imported: imported.sort(),
    skipped,
  }
  await writeFile(REPORT_PATH, renderImportReport(summary))
  return summary
}
